//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int iMaChatCode { get; set; }
        public string iNoiDung { get; set; }
        public Nullable<System.DateTime> dNgayLap { get; set; }
        public Nullable<int> iMaNguoiGuiCode { get; set; }
        public Nullable<int> iMaNguoiNhanCode { get; set; }
        public Nullable<int> iTrangThai { get; set; }
    }
}
