//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietLoi
    {
        public int iMaChiTietLoiCode { get; set; }
        public Nullable<int> iMaNhiemVuCode { get; set; }
        public string vTenLoi { get; set; }
        public string vChiTietLoi { get; set; }
        public Nullable<int> iTrangThai { get; set; }
    }
}
