//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhiemVu
    {
        public int iMaNhiemVuCode { get; set; }
        public string vTenNhiemVu { get; set; }
        public string vMoTa { get; set; }
        public Nullable<System.DateTime> dNgayLap { get; set; }
        public Nullable<System.DateTime> dNgayBD { get; set; }
        public Nullable<System.DateTime> dNgayKT { get; set; }
        public Nullable<int> iMaNguoiDangCode { get; set; }
        public Nullable<int> iMaNguoiDuocGiaoCode { get; set; }
        public Nullable<int> iMaTrangThaiCode { get; set; }
        public Nullable<int> iMaModuleCode { get; set; }
    }
}
