//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sb_admin.web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbnhiemvuEntities : DbContext
    {
        public dbnhiemvuEntities()
            : base("name=dbnhiemvuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCao> BaoCaos { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<ChiTietLoi> ChiTietLois { get; set; }
        public virtual DbSet<Hinh> Hinhs { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<NhiemVu> NhiemVus { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TapTin> TapTins { get; set; }
        public virtual DbSet<TapTinBaoCao> TapTinBaoCaos { get; set; }
        public virtual DbSet<ThanhVien> ThanhViens { get; set; }
        public virtual DbSet<ThanhVien_Quyen> ThanhVien_Quyen { get; set; }
        public virtual DbSet<TrangThai> TrangThais { get; set; }
        public virtual DbSet<HinhLoi> HinhLois { get; set; }
    }
}
